[colors]
[colors.primary]
background = "#002d38"
foreground = "#8faaab"

[colors.normal]
black   = "#093946"
red     = "#f23749"
green   = "#819500"
yellow  = "#ac8300"
blue    = "#2b90d8"
magenta = "#dd459d"
cyan    = "#259d94"
white   = "#f1e9d2"

[colors.bright]
black   = "#5b7279"
red     = "#d56500"
green   = "#5b7279"
yellow  = "#657377"
blue    = "#98a8a8"
magenta = "#7d80d1"
cyan    = "#8faaab"
white   = "#fbf7ef"

[colors.cursor]
text   = "#002d38"
cursor = "#8faaab"

[colors.selection]
background = "#093946"
text = "#98a8a8"
