accent = "#2b90d8"
cursor = "#8faaab"
foreground = "#8faaab"
background = "#002d38"
selection_foreground = "#98a8a8"
selection_background = "#093946"

color0 = "#093946"
color1 = "#f23749"
color2 = "#819500"
color3 = "#ac8300"
color4 = "#2b90d8"
color5 = "#dd459d"
color6 = "#259d94"
color7 = "#f1e9d2"
color8 = "#5b7279"
color9 = "#d56500"
color10 = "#5b7279"
color11 = "#657377"
color12 = "#98a8a8"
color13 = "#7d80d1"
color14 = "#8faaab"
color15 = "#fbf7ef"
