-- Generated by scripts/hypr2lua.
-- Source: omarchy-grimdark-solarized-theme/hyprland.conf

local activeBorderColor = "rgba(259d9488)"
local activeShadowColor = "rgba(259d9488)"
local inactiveBorderColor = "rgba(002d38aa)"
local inactiveShadowColor = "rgba(002d38aa)"

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
      inactive_border = inactiveBorderColor,
    },
    border_size = 2,
    gaps_in = 11,
    gaps_out = 22,
  },
  group = {
    col = {
      border_active = activeBorderColor,
      border_inactive = inactiveBorderColor,
    },
  },
  decoration = {
    rounding = 12,
    rounding_power = 3,
    inactive_opacity = 0.85,
    blur = {
      enabled = true,
      size = 2,
      passes = 3,
      vibrancy = 0.3,
      vibrancy_darkness = 0.3,
      noise = 0.2645,
    },
    shadow = {
      enabled = true,
      range = 14,
      render_power = 2,
      color = activeShadowColor,
      color_inactive = inactiveShadowColor,
    },
  },
})
